version: '3.8'
services:
  taskmanagement:
      build: .
      container_name: taskmanagement
      depends_on:
          - 'postgres'
      environment:
          - PORT=3000
          - RDS_HOSTNAME=postgres
          - RDS_PORT=5432
          - RDS_USERNAME=postgres
          - RDS_PASSWORD=postgres
          - RDS_DATABASE=taskmanagement
          - TYPEORM_SYNC=true
          - JWT_SECRET=spin
          - NODE_CONFIG_DIR=/usr/src/app/config
      ports:
          - '3000:3000'
      volumes:
          - './:/usr/src/app'
      stdin_open: true
      tty: true
  postgres:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=taskmanagement
    ports:
    - '5432:5432'
    volumes: 
    - postgresdb:/var/lib/postgresql/data
    stdin_open: true
    tty: true
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
    - pgadmin:/root/.pgadmin
    ports:
    - "8082:80"
    depends_on:
        - 'postgres'
    restart: always
volumes:
  postgresdb:
    driver: local
  pgadmin:
    driver: local

