version: '3.8'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=taskmanagement
    ports:
    - '5432:5432'
    volumes: 
    - postgresdb:/var/lib/postgresql/data
    stdin_open: true
    tty: true
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
    - pgadmin:/root/.pgadmin
    ports:
    - "8082:80"
    depends_on:
        - 'postgres'
    restart: always
volumes:
  postgresdb:
    driver: local
  pgadmin:
    driver: local

